# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!
target 'OC' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  # Pods for OC
  pod 'Masonry', '~> 1.1.0'
  pod 'YYModel', '~> 1.0.4'
  pod 'HandyJSON'
  pod 'TZImagePickerController'        # Full version with all features      
  #pod 'TZImagePickerController/Basic'  # No location code
end
