# Uncomment the next line to define a global platform for your project

source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'Web3Wallet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Web3Wallet
#pod 'Web3.swift'
pod 'EthereumKit'
pod 'web3swift'
pod 'BitcoinKit'

end
